-- supabase/schema.sql
-- Im Supabase SQL-Editor unter: Project → SQL Editor → New Query einfügen und ausführen

-- Products
create table if not exists products (
  id bigint generated by default as identity primary key,
  name text not null,
  gebinde jsonb not null default '[]'::jsonb,
  created_at timestamptz default now()
);

-- Events
create table if not exists events (
  id bigint generated by default as identity primary key,
  name text not null,
  date_start date,
  date_end date,
  product_ids bigint[] not null default '{}'::bigint[],
  created_at timestamptz default now()
);

-- Fridges
create table if not exists fridges (
  id bigint generated by default as identity primary key,
  event_id bigint references events(id) on delete cascade,
  type text not null,
  label text not null,
  created_at timestamptz default now()
);
create index if not exists fridges_event_id_idx on fridges(event_id);

-- Sessions
create table if not exists sessions (
  id bigint generated by default as identity primary key,
  event_id bigint references events(id) on delete cascade,
  fridge_id bigint references fridges(id) on delete cascade,
  timestamp bigint not null,
  label text not null,
  entries jsonb not null default '[]'::jsonb,
  created_at timestamptz default now()
);
create index if not exists sessions_fridge_id_idx on sessions(fridge_id);
create index if not exists sessions_event_id_idx on sessions(event_id);

-- Fridge Locks (ein Lock pro Kühlgerät gleichzeitig)
create table if not exists fridge_locks (
  id bigint generated by default as identity primary key,
  fridge_id bigint references fridges(id) on delete cascade unique,
  event_id bigint references events(id) on delete cascade,
  locked_by text not null,
  locked_by_name text not null default 'Unbekannt',
  locked_at timestamptz default now()
);

-- Session Photos
create table if not exists session_photos (
  id bigint generated by default as identity primary key,
  session_id bigint references sessions(id) on delete cascade,
  storage_path text not null,
  created_at timestamptz default now()
);

-- Event Access Codes (QR-Codes für Teamzugang)
create table if not exists event_access_codes (
  id bigint generated by default as identity primary key,
  event_id bigint references events(id) on delete cascade,
  code text not null unique,
  valid_from timestamptz not null,
  valid_until timestamptz not null,
  created_at timestamptz default now()
);

-- RLS aktivieren (Policies kommen in späteren Tasks)
alter table products enable row level security;
alter table events enable row level security;
alter table fridges enable row level security;
alter table sessions enable row level security;
alter table fridge_locks enable row level security;
alter table session_photos enable row level security;
alter table event_access_codes enable row level security;

-- Temporäre offene Policies (bis Auth fertig ist — NICHT für Produktion)
-- Diese werden in Phase C durch echte RLS-Policies ersetzt
create policy "temp_open_products" on products for all using (true) with check (true);
create policy "temp_open_events" on events for all using (true) with check (true);
create policy "temp_open_fridges" on fridges for all using (true) with check (true);
create policy "temp_open_sessions" on sessions for all using (true) with check (true);
create policy "temp_open_fridge_locks" on fridge_locks for all using (true) with check (true);
create policy "temp_open_session_photos" on session_photos for all using (true) with check (true);
create policy "temp_open_access_codes" on event_access_codes for all using (true) with check (true);

-- Storage Bucket für Fotos (separat im Supabase Dashboard anlegen unter Storage → New Bucket)
-- Bucket-Name: "session-photos", Public: false
